// Code generated by gobind. DO NOT EDIT.

// Java class PixivLocalReverseProxy.PixivLocalReverseProxy is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java pixiv-local-reverse-proxy
package PixivLocalReverseProxy;

import go.Seq;

public abstract class PixivLocalReverseProxy {
	static {
		Seq.touch(); // for loading the native library
		_init();
	}
	
	private PixivLocalReverseProxy() {} // uninstantiable
	
	// touch is called from other bound packages to initialize this package
	public static void touch() {}
	
	private static native void _init();
	
	
	
	public static native void startServer(String bindPort);
	public static native void stopServer();
}
